Web/Web/Controllers/EditController.cs
using Common;
using Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    [Authorize]
    public class EditController : BaseController
    {
        [HttpGet]
        public ActionResult Index(int verseId, string returnUrl)
        {
            using (var context = new QuranicHarfDbContext())
            {
                var verse = context.Verses.Find(verseId);
                var model = new EditModel()
                {
                    VerseId = verse.Id,
                    OriginalText = verse.OriginalText,
                    VerseText = verse.VerseText,
                    OriginalVerseText = verse.VerseText,
                    ReturnUrl = returnUrl,
                    SurahName = context.Surahs.SingleOrDefault(s => s.SurahNo == verse.SurahNo).EnglishName,
                    SurahNo = verse.SurahNo,
                    VerseNo = verse.VerseNo,
                    CurrentState = EditingState.Edit
                };
                model.HistoryModel = GetHistory(verse ,context);

                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Index(EditModel model)
        {
            using (var context = new QuranicHarfDbContext())
            {
                var verse = context.Verses.Find(model.VerseId);
                if (model.OriginalVerseText == model.VerseText)
                {
                    model.WarningMessage = "Nothing to save. Please make valid changes before clicking \"Preview\" button. Otherwise click \"Cancel\" to return to previous page.";
                }
                else if (model.CurrentState == EditingState.Edit && model.RequestedState == EditingState.Preview)
                {
                    // harfs = harfsCache = TextFormatter.ParseWithHarkat(originalVerseText);
                    model.OriginalLines = new HarfInBoxModel()
                    {
                        AllLines = new List<LineModel>() { GenerateLine(verse) },
                        ShowEditIcon = false
                    };
                    model.PreviewLines = new HarfInBoxModel()
                    {
                        AllLines = new List<LineModel>() { GenerateLineForPreview(verse, model.VerseText) },
                        ShowEditIcon = false
                    };
                    model.CurrentState = EditingState.Preview;
                }
                else if (model.CurrentState == EditingState.Preview && model.RequestedState == EditingState.Save && model.ConfirmCheck == true)
                {
                    verse.VerseText = model.VerseText;
                    verse.EditedDate = DateTime.UtcNow;
                    verse.EditedBy = HttpContext.User.Identity.Name;

                    string[] harfs = TextFormatter.ParseWithHarkat(model.VerseText);
                    int harfCount = harfs.Where(h => h != " ").Count();
                    if (harfCount == verse.HarfCount)
                    {
                        DoVerseCounterRecalculation(verse, context, harfs);
                        verse.IsRecalculationRequired = false;
                    }
                    else
                    {
                        verse.IsRecalculationRequired = true;
                    }

                    SearchFilter searchFilter = CalculateSearchFilter();
                    // TODO: show sourceName in edit page 
                    var editHistory = new VerseEditHistory()
                    {
                        SourceId = searchFilter.SourceId,
                        VerseNo = verse.VerseNo,
                        SurahNo = verse.SurahNo,
                        EditedText = verse.VerseText,
                        EditedBy = HttpContext.User.Identity.Name,
                        EditedDate = DateTime.UtcNow
                    };

                    context.VerseEditHistories.Add(editHistory);
                    context.SaveChanges();

                    model.SuccessMessage = "Your changes saved successfully.";
                    model.OriginalText = verse.OriginalText;
                    model.CurrentState = EditingState.Save;

                }
                else if (model.CurrentState == EditingState.Preview && model.RequestedState == EditingState.Edit)
                {
                    model.CurrentState = EditingState.Edit;
                }
                // Create a partial _VerseEditHistory view which will take EditHistoryModel 
                model.HistoryModel = GetHistory(verse, context);
            }
            return View(model);
        }

        private VerseEditHistoryModel GetHistory(Verse verse,QuranicHarfDbContext context)
        {
            return new VerseEditHistoryModel()
            {
                Histories = context.VerseEditHistories.Where(VE => VE.VerseNo == verse.VerseNo && VE.SurahNo == verse.SurahNo && VE.SourceId == verse.SourceId).OrderByDescending(h => h.EditedDate).ToList()
            };
        }

        private void DoVerseCounterRecalculation(Verse verse, QuranicHarfDbContext context, string[] harfs)
        {
            context.VerseHarfs.RemoveRange(context.VerseHarfs.Where(h => h.VerseId == verse.Id));
            int verseHarfSerial = 1;
            int verseHarfCounter = 0;
            foreach (string harf in harfs)
            {
                var item = new VerseHarf()
                {
                    HarfText = harf,
                    Serial = verseHarfSerial++,
                    VerseId = verse.Id,
                    LocalCounter = harf == " " ? 0 : verse.StartSurahCounter + verseHarfCounter,
                    GlobalCounter = harf == " " ? 0 : verse.StartGlobalCounter + verseHarfCounter
                };
                if (harf != " ") verseHarfCounter++;
                context.VerseHarfs.Add(item);
            }
        }

    }
}

Web/Web/Views/Shared/_HarfInBox.cshtml
@using Web.Models
@using Data

@model  HarfInBoxModel

@foreach (LineModel line in Model.AllLines)
{
    <div class="row verse-line">
        @{
            int lineLenght = line.Harfs.Length;
            string elementId = "verse_" + line.SurahNo + "_" + line.VerseNo;
        }

        <div id="@elementId" class="surah-verse-no">
            @(line.SurahNo + ":" + line.VerseNo)
            @if (HttpContext.Current.User.Identity.IsAuthenticated && Model.ShowEditIcon)
                {
                <a href="@Url.Action("Index", "Edit", new { verseId = line.VerseId, returnUrl = Request.RawUrl + "#" + elementId})" class="glyphicon glyphicon-edit icon-space edit-link" title="Edit this verse"></a>
            }
        </div>

        @foreach (VerseHarf harf in line.Harfs)
        {
            if (harf.HarfText == " ")
            {
                <div style="float:right; width:50px; border: 1px solid #F0F0F0; margin-bottom:10px;">
                    <div class="row" style="padding:5px; text-align:center;">&nbsp;</div>
                    <div class="row" style="padding:5px; text-align:center; font-size:3em;">&nbsp;</div>
                    <div class="row" style="padding:5px; text-align:center;">&nbsp;</div>
                </div>
            }
            else
            {
                bool isHighlight = false;
                if (ViewBag.GlobalHarfPositions != null)
                {
                    isHighlight = ((List<int>)ViewBag.GlobalHarfPositions).Contains(harf.GlobalCounter);
                }
                <div class="single-harf @( isHighlight ? "highlight" : "")" style="float:right; min-width:50px; border: 1px solid #F0F0F0; margin-bottom:10px;">
                    <div class="row" id="localcounter" style="padding:5px; min-width:50px; text-align:center;">@harf.LocalCounter</div>
                    <div class="row"  style="padding:5px; min-width:50px; text-align:center; font-size:3em;">@harf.HarfText</div>
                    <div class="row" id="globalcounter"style="padding:5px; min-width:50px; text-align:center;">@harf.GlobalCounter</div>
                </div>
            }
        }
        @*<div style="float:right; width:50px; ">
            <span class="end-of-verse"> @ConvertNumerals.Convert(line.VerseNo.ToString())  </span>
        </div>*@

        <div style="float:right; width:50px; ">
            <span class="end-of-verse"> @line.VerseNo.ToString()  </span>
        </div>

        <hr class="h-line dark-bold" />

    </div>
}

Web/Web/Views/Shared/_Header.cshtml
@using Web.Models
@using Data
@model ISurahSearchable
    @{ 
        var filter = Model.SearchFilter;
    }

<div class="row alert-info">
    <div class="col-md-12">
        <a class="glyphicon glyphicon-home icon-space no-underline" href="@Url.Action("Index", "Home")" title="Go to home">&nbsp;Home</a>
        <a class="glyphicon glyphicon-plus icon-space no-underline" id="Switch" data-toggle="collapse" href="#FilterForm" aria-expanded="false" aria-controls="FilterForm" title="Show filters">&nbsp;Filters</a>
        <a class="glyphicon glyphicon-question-sign icon-space no-underline" href="javascript:StartGuidedTour('@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()');" title="Start Guided Tour">&nbsp;Help</a>
        <a class="glyphicon glyphicon-stats icon-space no-underline" id="StatLink" href="@(Url.Action("Index", "Stat") + "?" + Request.QueryString)" title="View Statistics">&nbsp;Statistics</a>
    </div>
</div>

<div class="spacer"></div>

<div class="jumbotron collapse multi-collapse" id="FilterForm">

    <form action="@Model.SearchToUrl" method="get">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="SelectSurahFrom">Surah From:</label>
                    <select class="form-control" id="SelectSurahFrom" name="ss">
                        <option>Select....</option>
                        @foreach (Surah surah in Model.SurahList)
                        {
                            <option value="@surah.SurahNo" @(surah.SurahNo == filter.StartSurahNo ? "selected" : "")>
                                @surah.EnglishName - @surah.ArabicName
                            </option>

                        }
                    </select>
                </div>


            </div>

            <div class="col-sm-4">
                <div class="form-group">
                    <label for="SelectSurahTo">Surah To:</label>
                    <select class="form-control" id="SelectSurahTo" name="es">
                        <option>Select....</option>
                        @foreach (Surah surah in Model.SurahList)
                        {
                            <option value="@surah.SurahNo" @(surah.SurahNo == filter.EndSurahNo ? "selected" : "")>
                                @surah.EnglishName - @surah.ArabicName
                            </option>
                        }
                    </select>
                </div>


            </div>

            <div class="col-sm-4">
                <div class="form-group">
                    <label for="SelectSingleHarf">Select Harf:</label>
                    <select class="form-control" id="SelectSingleHarf" name="h">
                        <option value="">Select...</option>
                        @foreach (string harf in Model.HarfFilterItems)
                        {
                            <option value="@harf" @(harf == filter.SpecificHarf ? "selected" : "")>
                                @harf
                            </option>
                        }
                    </select>
                </div>
            </div>


            <div class="col-sm-4 form-group">
                <label for="StartVerseNo">Verse From</label>
                <input type="text" class="form-control" id="StartVerseNo" name="sv" value="@(filter.StartVerseNo)" />
            </div>
            <div class="col-sm-4 form-group">
                <label for="EndVerseNo">Verse To</label>
                <input type="text" id="EndVerseNo" class="form-control" name="ev" value="@(filter.EndVerseNo)" />
            </div>

            <div class="col-sm-4">
                <div class="form-group">
                    <label for="SelectSource">Select Sourcce:</label>
                    <select class="form-control" id="SelectSource" name="src">
                        <option value="">Select...</option>
                        @foreach (KeyValuePair<int, string> source in Model.SourceItems)
                        {
                            <option value="@source.Key" @(source.Key == filter.SourceId ? "selected" : "")>
                                @source.Value
                            </option>
                        }
                    </select>
                </div>
            </div>

            <div class="col-sm-4">
                <input class="btn btn-primary" type="submit" value="Submit" />
            </div>
        </div>


    </form>

</div>

Web/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Quranic Harf</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Quranic-Harf", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                @RenderSection("NavBarSummary", false)

                @*<ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>*@
                @Html.Partial("_LoginPartial")
               
            </div>
        </div>
    </div>
    <div class="container body-content" style="padding:30px 0px 0px 0px ">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>

    <input type="hidden" id="RecalcUrl" value="@(Url.Action("Try", "Recalc") + "?" + Request.QueryString)" />

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")


    <script src="@Url.Content("~/Scripts/bootstro.js")"></script>
    <link href="http://clu3.github.io/bootstro.js/bootstro.css" rel="stylesheet">

    @RenderSection("scripts", required: false)
    <script src="@Url.Content("~/Scripts/main.js")"></script>

</body>
</html>

Web/Web/Views/Shared/_VerseEditHistory.cshtml
@using Data
@model Web.Models.VerseEditHistoryModel


<table class="table table-bordered">
    <thead>
        <tr>
            <th>Date</th>
            <th>Edited By</th>
            <th>Edited Text</th>
        </tr>
    </thead>
    <tbody>
        @foreach (VerseEditHistory history in Model.Histories)
        {
            <tr>
                <td>@history.EditedDate</td>
                <td>@history.EditedBy</td>
                <td>@history.EditedText</td>
            </tr>
        }

    </tbody>
</table>